"""Add floor column to room

Revision ID: d73401ff985a
Revises: 2d50eecffb62
Create Date: 2026-06-08 11:16:37.161870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73401ff985a'
down_revision = '2d50eecffb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('floor', sa.Integer(), nullable=True))
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('floor')

    # ### end Alembic commands ###
